### ISSUE TITLE
Package is installed as "src"

### ISSUE THREAD

**Issue by treyhunner** [PyBites-Open-Source/pysource#2]
After installing, the command-line program `pysource` exists:

```bash
$ pysource
usage: pysource [-h] -m MODULE [-p]
pysource: error: the following arguments are required: -m/--module
```

But I'd expect this to work and it doesn't:

```bash
$ python -m pysource
/home/trey/.pyenv/versions/3.9.0/bin/python: No module named pysource
```

And further inspection shows that there isn't actually a `pysource` module:

```pycon
>>> import pysource
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pysource'
```

There's a `src` module instead:

```pycon
>>> import src
```

And you can run the module `src` from the command-line:

```bash
$ python -m src
usage: __main__.py [-h] -m MODULE [-p]
__main__.py: error: the following arguments are required: -m/--module
```

**Comment by bbelderbos** [comment]
Good catch @treyhunner, I will rename `src` to `pysource`. Also better for how it ends up in `site-packages`. Thanks

**Comment by bbelderbos** [comment]
All good to go: https://pypi.org/project/pybites-pysource/1.1.0/

Commit: https://github.com/PyBites-Open-Source/pysource/commit/7a2b8dae046280530e3e558a52a141d52422e435

Also added a module test discovering something interesting about `this`:
https://github.com/PyBites-Open-Source/pysource/commit/be7e6505dfbd618f43b6ebd33335253c6dc0999e
